media:
  folder: images
content:
  - name: gallery
    label: ЁЯУ╖ ржорж┐ржбрж┐рзЯрж╛ ржЧрзНржпрж╛рж▓рж╛рж░рж┐ (ржЫржмрж┐ ржЖржкрж▓рзЛржб)
    type: file
    file: gallery.json
    fields:
      - name: photos
        label: ржЖржкржирж╛рж░ ржЧрзНржпрж╛рж▓рж╛рж░рж┐рж░ ржЫржмрж┐рж╕ржорзВрж╣
        type: list
        fields:
          - name: title
            label: ржЫржмрж┐рж░ ржХрзНржпрж╛ржкрж╢ржи (Title)
            type: string
          - name: image
            label: ржЫржмрж┐ ржЖржкрж▓рзЛржб ржХрж░рзБржи (Image)
            type: image
